
[tools]
"cargo:lq" = "latest"
fd = "latest"
# gemini-cli = "latest"
gemini = "latest"
jqp = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
mkcert = "latest"
neovim = "latest"
# mongosh = "latest"
node = "latest"
# nodejs = "latest"
python = "latest"
ruby = "latest"
sqlite = "latest"
rust = "latest"
terraform = "latest"
zellij = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
